### PR TITLE
GH-89: Add build script warnings for failed modules builds

### PR DESCRIPTION
**Pull request by Forsinge**
Resolves: #89 

This PR adds warnings in the build script for when modules fail to build.

### CODE REVIEW

**Review by adelhult — APPROVED** [review]
Looks good!

**Comment by CMDJojo** [comment]
Isn't it better if the compilation fails alltogether (i.e an warning instead of an error), if possible?

**Comment by CMDJojo** [comment]
(If that isn't possible or hard to do, feel free to merge this; the compilation will fail anyways and thus the logs may show what module is problematic, which is much better than we had before)

**Comment by Forsinge** [comment]
I think it may be possible, at the very least with a ``panic!``. One disadvantage of doing that is when several modules fail to build. In this case you would only be notified about one.

**Comment by CMDJojo** [comment]
Yeah, that is true. Keep it as we have it now then. Good work!

**Pull request merged**
