### PR TITLE
GH-112: Add latex support to table

### PR DESCRIPTION
**Pull request by bruhng**
- Resolves: GH-112
Adds support for table->Latex

image

image

### CODE REVIEW

**Review by CMDJojo — CHANGES_REQUESTED** [review]
It is nice to have LaTeX output support for tables! However, I think there are some parts here that can be improved.

The task of the Table module is two-split:
 - Parse the content, pick out what the cells are, their content etc etc.
 - Render the content in the output format of choice

The first part, parsing, is probably the more complicated part. Rendering in HTML is just adding some <table>-tags and in LaTeX, it is adding some \begin{tabular} etc. The parsing part should be common between the two output formats; the syntax and semantics of the input to the table module should result in the same content, regardless of the output format. We currently have a pretty simple parser, but #94 aims to add a more complicated parser. I think it is a bad idea to just copy-paste the parser between the LaTeX and HTML implementation as you do now, since that could result in different results depending on the output format, which is not wanted.

You could do this by returning a custom node that contains the parsed content, which gets handled by this package later, like a `__table_ir` node, and define a transform `__table_ir` to HTML and LaTeX. Another alternative would be to just create a custom struct holding the parsed table, make a function that parses the table into that struct, and use that function both when outputting LaTeX and HTML. Both these ways would ensure that there is one common parser and that the parsing code is synchronized between the two different output formats.

**Comment by bruhng** [comment]
https://github.com/modmark-org/modmark/pull/124#pullrequestreview-1320096925

Of course it would be better to link the parsing of the two, this was just a temporary solution to be able to render the example document in Latex.

**Comment by bruhng** [comment]
Moved out the parsing part, is this better?

**Comment by bruhng** [comment]
Fixed according to clippy

**Comment by CMDJojo** [comment]
Yes, that seems much better! I would also love some tests to verify that it works correctly and as expected, so that if further changes are done, we can be sure that it didn't break anything or created invalid JSON.

**Comment by CMDJojo** [comment]
I think we can close this since #150 is merged

**Pull request closed without merging**
