### PR TITLE
Add CI for check/test/clippy/fmt

### PR DESCRIPTION
**Pull request by CMDJojo**
This PR attempts to use GitHub Actions as a CI for all pull requests and commits to main. To do this, two things have been done:
1. One Cargo Workspace has been added containing all four crates as members (and a `.gitignore` was added)
2. A `RustCI.yml` file was created under `.github/workflows` based on [this](https://github.com/modmark-org/modmark/issues/3#issuecomment-1398769696) comment from @axoxelol1 (some adjustments were made; names were added, toolchain installation was streamlined and more verbosity was added). But that gist was of good help!

The CI runs `check`, `test` , `clippy` and `fmt`.
I am unsure if this PR will actually check if the CI workflow works, but let's hope!

Resolves GH-3

### CODE REVIEW

**Comment by axoxelol1** [comment]
We are getting some warning annotations when the CI runs due to actions depending on node 12.
>Code.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Checkout could be updated to v3 to avoid this but I cannot find anything about updates to actions-rs. I didn't notice them when I made the gist. I think we could just ignore them for now and look at it again later.

**Comment by CMDJojo** [comment]
Hmm, seems strange…didn’t notice those warnings at first. Thanks for the heads up! I can see what I find later today. Is there a good way to test-run the actions without pushing it to remote?Anyways, I think it is fine to ignore for now, and if anyone finds a solution, we can just reference this PR and the original issue from the new PR.For this to be merged, however, it would be nice if GH-7 gets approved first, since this builds on it.On 22 Jan 2023, at 20:20, axoxelol1 ***@***.***> wrote:﻿
We are getting some warning annotations when the CI runs due to actions depending on node 12.

Code.js 12 actions are deprecated. Please update the following actions to use Node.js 16: ***@***.***, ***@***.***, ***@***.*** For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Checkout could be updated to v3 to avoid this but I cannot find anything about updates to actions-rs. I didn't notice them when I made the gist. I think we could just ignore them for now and look at it again later.

**Comment by CMDJojo** [comment]
@axoxelol1 regarding your previous comment:
> We are getting some warning annotations when the CI runs due to actions depending on node 12.

I have now updated checkout to use v3, and changed `actions-rs/*` to [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) and `run`. According to an [issue](https://github.com/actions-rs/cargo/issues/222) on the `actions-rs/cargo` task we previously used, that repo isn't maintained anymore. Thank you for the heads-up, would have missed the warnings otherwise! I cannot see any more warnings on the new run with the new CI, and if you think it looks okay, I think we are ready for merging!

**Comment by CMDJojo** [comment]
We could also just `run` all the tasks sequentially and then not having to set up the toolchain one time for each job, but I think that it isn't worth it since the toolchain setup only takes 1s and accounts for ≈3% of the total runtime for most jobs, and with that little CI time, it is more worth to get the jobs done quicker in my opinion, but please tell me if you disagree!

**Review by axoxelol1 — APPROVED** [review]

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Review by axoxelol1 — APPROVED** [review]
lgtm

**Pull request merged**
